steps:
#First Clone from Google Cloud Source Repository  
- name: 'gcr.io/festive-canto-301306/helloworldtanmoy:3'
  args: ['clone','https://source.developers.google.com:2022/p/festive-canto-301306/r/github_tanmoynandy_helloworlddocker']

#Build the image s
- name: 'gcr.io/festive-canto-301306/helloworldtanmoy'
  args: ['build','-t','gcr.io/festive-canto-301306/helloworldtanmoy:3','.']

#Push the image  
- name: 'gcr.io/festive-canto-301306/helloworldtanmoy'
  args: ['push','gcr.io/festive-canto-301306/helloworldtanmoy:3']
  
#Update the container image using kubectl set
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'set'
  - 'image'
  - 'deployment/helloworlddeployment'
  - 'helloworldtanmoy=gcr.io/festive-canto-301306/helloworldtanmoy:3'